# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b4c2e999e67169d89e40e23a232d61dedb2290feba4e376027510801fc12c8f0c537662bac635cd50af5f19ff81c8f73b824811201c8be8fede63f20008157c

test:
  secret_key_base: d3cda6ab661e7af97d484965f7fe765db57d57470f763c05d4eed4c974ef6fd2ac57733e18cac531db08434ca2fa2795f72cbf099088a6ae67149aeb082ffaaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
